
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:bt itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bt>


<field:nr itemname="内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nr>

<field:add itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:add>
