<?php
$z[0]=Array("channel","\r\n      <li><a href='[field:typeurl/]' title='[field:typename/]'>[field:typename/]</a></li>\r\n      ",97,236);
$z[0][4]['type']="top";
$z[1]=Array("global","",340,366);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",399,420);
$z[2][4]['name']="cfg_mc";
$z[3]=Array("global","",442,463);
$z[3][4]['name']="cfg_sj";
$z[4]=Array("global","",485,506);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",530,551);
$z[5][4]['name']="cfg_dz";

?>